'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    async up(queryInterface, Sequelize) {
        /**
         * Add seed commands here.
         */

        let data = [];

        function set_data(
            id,
            branch_id,
            parent_id,
            title,
            description,
            count_id,
            sort_code,
            account_code,
            balance,
            note,
            system_ip,
            system_name,
            delete_bit,
            account_selection_name,
            payments_type_id,
            customer_id,
            supplier_id,
            expense_id,
        ) {
            data.push({
                id,
                branch_id,
                parent_id,
                title,
                description,
                count_id,
                sort_code,
                account_code,
                balance,
                note,
                system_ip,
                system_name,
                delete_bit,
                account_selection_name,
                payments_type_id,
                customer_id,
                supplier_id,
                expense_id,
                created_at: '2024-02-14',
                updated_at: '2024-02-14',
            });
        }

        // Realistic account category titles
        const accountCategories = [
            'Cash on Hand',
            'Bank Account',
            'Accounts Receivable',
            'Inventory - Finished Goods',
            'Accounts Payable',
            'Sales Revenue',
            'Cost of Goods Sold',
            'Operating Expenses',
            'Loan Payable',
            'Retained Earnings',
        ];

        // Generating 10 realistic records
        for (let i = 1; i <= 10; i++) {
            set_data(
                i, // Auto-increment ID
                Math.floor(Math.random() * 5) + 1, // Random branch_id
                i > 5 ? Math.floor(Math.random() * 5) + 1 : null, // Parent ID for some categories
                accountCategories[i - 1], // Realistic title
                `This is the account for ${accountCategories[i - 1]}`,
                i, // count_id (same as id for now)
                Math.floor(Math.random() * 10) + 1, // Random store_id
                `SC-${1000 + i}`,
                `AC-${2000 + i}`,
                // (Math.random() * 50000).toFixed(2), // Random balance
                'Generated by Seeder',
                '192.168.1.1', // System IP
                'Server01', // System Name
                0, // Not deleted
                'Default Account',
                Math.floor(Math.random() * 5) + 1, // Random payments_type_id
                Math.floor(Math.random() * 10) + 1, // Random customer_id
                Math.floor(Math.random() * 10) + 1, // Random supplier_id
                Math.floor(Math.random() * 10) + 1, // Random expense_id
            );
        }

        await queryInterface.bulkDelete('account_categories', null, {});
        await queryInterface.bulkInsert('account_categories', data, {});
    },

    async down(queryInterface, Sequelize) {
        /**
         * Add commands to revert seed here.
         */
        await queryInterface.bulkDelete('account_categories', null, {});
    },
};
