@hostname = http://127.0.0.1:5002/api/v1/account-logs
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidG9rZW4iOiJlOHYwZXZrYyIsInVzZXJfYWdlbnQiOiJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTMxLjAuMC4wIFNhZmFyaS81MzcuMzYiLCJ1c2VyX3R5cGUiOiJzdGFmZiIsImlhdCI6MTczMjQxOTEyN30.o9VedKOMPtQRI8UyZd1fFBdLtmmG-SiM9S1OcE3LOqI

# all
###
GET {{hostname}}?orderByCol=id&orderByAsc=true&show_active_data=true&paginate=10 HTTP/1.1

# get
###
GET {{hostname}}/periods HTTP/1.1

# get
###
GET {{hostname}}/credit HTTP/1.1

# get
###
GET {{hostname}}/month-wise-statement HTTP/1.1

# get
###
GET {{hostname}}/income-statement HTTP/1.1

# get
###
POST {{hostname}}/journal HTTP/1.1

# get
###
GET {{hostname}}/debit HTTP/1.1

# get
###
GET {{hostname}}/receipt-book HTTP/1.1

# get
###
GET {{hostname}}/account/1 HTTP/1.1

# get
###
GET {{hostname}}/categories HTTP/1.1

# store
###
POST  {{hostname}}/store HTTP/1.1
content-type: application/json

{
    "branch_id": 4,
    "title": "cellphin",
    "description": "This is sellfin accoutn"
}

# store
###
POST  {{hostname}}/expense-store HTTP/1.1
content-type: application/json

{
    "branch_id": 1,
    "account_category_id": 1,
    "account_id": 1,
    "account_period_id": 1,
    "money_receipt_book_id": 1,
    "receipt_no": "A123",
    "date": "2024-09-11T00:00:00.000Z",
    "amount": 544,
    "type": "dfgfgdffgdf",
    "amount_in_text": "Twenty thousand taka only"
}

# store
###
POST  {{hostname}}/fees-collection HTTP/1.1
content-type: application/json

{
    "branch_id": 1,
    "student_id": 1,
    "class_id": 1,
    "account_category_id": 1,
    "account_id": 1,
    "account_period_id": 1,
    "money_receipt_book_id": 1,
    "accounts_title": "Bank",
    "accounts_description": "Islami bank account",
    "ap_year_month": "2024-02-14",
    "afc_date": "2024-02-14",
    "ap_description": "Islami bank account",
    "ac_title": "Admission bill",
    "ac_description": "This is admission bill",
    "al_amount": "2000",
    "afc_amount": "2000",
    "receipt_no": "001",
    "al_type": "income",
    "mrb_book_no": "A101",
    "mrb_start_serial": "101",
    "mrb_end_serial": "200"
}


# update
###
POST {{hostname}}/update HTTP/1.1 
content-type: application/json

{
    "id": 4,
    "branch_id": "4",
    "title": "sellfin",
    "description": "This is sellfin account"
}

# delete
###
POST  {{hostname}}/soft-delete HTTP/1.1
content-type: application/json

{
    # "id": 4
}

# restore
###
POST  {{hostname}}/restore HTTP/1.1
content-type: application/json

{
    "id": 4
}


# destroy
###
POST  {{hostname}}/destroy HTTP/1.1
content-type: application/json

{
    "id": 4
}